/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.util.Criptografia;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Vandre
 */
public class dialogGerarSenha extends javax.swing.JDialog {
    
    /**
     * Creates new form GerarSenha
     * @param parent
     * @param modal
     */
    public dialogGerarSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private void gerarBcrypt() {
        if (passwordFieldSenha.getText().compareTo(passwordFieldConfirme.getText()) == 0) {
            textFieldSenhaGerada.setText(Criptografia.hash(passwordFieldSenha.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "Senhas não conferem.");
        }
    }
    
    private void gerarAES() {
        if (passwordFieldSenha.getText().compareTo(passwordFieldConfirme.getText()) == 0) {
            byte b[] = null;
            try {
                b = Criptografia.encrypt(passwordFieldSenha.getText());
            } catch (Exception ex) {
                Logger.getLogger(dialogGerarSenha.class.getName()).log(Level.SEVERE, null, ex);
            }
            String senha = "{ ";
            for(int i=0; i<b.length; i++) {
                senha = senha + b[i];
                if (i<b.length-1)
                    senha = senha + ",";
            }
            senha = senha + "}";
            textFieldSenhaGerada.setText(senha);
        } else {
            JOptionPane.showMessageDialog(null, "Senhas não conferem.");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSenha = new javax.swing.JLabel();
        labelConfirme = new javax.swing.JLabel();
        passwordFieldSenha = new javax.swing.JPasswordField();
        passwordFieldConfirme = new javax.swing.JPasswordField();
        buttonAES = new javax.swing.JButton();
        buttonFechar = new javax.swing.JButton();
        textFieldSenhaGerada = new javax.swing.JTextField();
        labelSenhaGerada = new javax.swing.JLabel();
        buttonBCrypt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSenha.setText("Senha:");
        getContentPane().add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        labelConfirme.setText("Confirme:");
        getContentPane().add(labelConfirme, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        passwordFieldSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldSenhaFocusGained(evt);
            }
        });
        passwordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(passwordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 240, -1));

        passwordFieldConfirme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldConfirmeFocusGained(evt);
            }
        });
        getContentPane().add(passwordFieldConfirme, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 240, -1));

        buttonAES.setText("AES");
        buttonAES.setPreferredSize(new java.awt.Dimension(90, 35));
        buttonAES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAESMouseClicked(evt);
            }
        });
        getContentPane().add(buttonAES, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        buttonFechar.setText("Fechar");
        buttonFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        buttonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFecharMouseClicked(evt);
            }
        });
        getContentPane().add(buttonFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        textFieldSenhaGerada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldSenhaGeradaFocusGained(evt);
            }
        });
        getContentPane().add(textFieldSenhaGerada, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 319, -1));

        labelSenhaGerada.setText("Senha");
        getContentPane().add(labelSenhaGerada, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        buttonBCrypt.setText("BCrypt");
        buttonBCrypt.setPreferredSize(new java.awt.Dimension(90, 35));
        buttonBCrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBCryptMouseClicked(evt);
            }
        });
        getContentPane().add(buttonBCrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAESMouseClicked
        gerarAES();
    }//GEN-LAST:event_buttonAESMouseClicked

    private void buttonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFecharMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_buttonFecharMouseClicked

    private void passwordFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldSenhaKeyPressed
        int key = evt.getKeyCode();
        //tecla enter pressionada
        if (key == KeyEvent.VK_ENTER) {
            passwordFieldConfirme.requestFocus();
        }
    }//GEN-LAST:event_passwordFieldSenhaKeyPressed

    private void buttonBCryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBCryptMouseClicked
        gerarBcrypt();
    }//GEN-LAST:event_buttonBCryptMouseClicked

    private void passwordFieldSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldSenhaFocusGained
        passwordFieldSenha.selectAll();
    }//GEN-LAST:event_passwordFieldSenhaFocusGained

    private void passwordFieldConfirmeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldConfirmeFocusGained
        passwordFieldConfirme.selectAll();
    }//GEN-LAST:event_passwordFieldConfirmeFocusGained

    private void textFieldSenhaGeradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldSenhaGeradaFocusGained
        textFieldSenhaGerada.selectAll();
    }//GEN-LAST:event_textFieldSenhaGeradaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogGerarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogGerarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogGerarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogGerarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogGerarSenha dialog = new dialogGerarSenha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAES;
    private javax.swing.JButton buttonBCrypt;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JLabel labelConfirme;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSenhaGerada;
    private javax.swing.JPasswordField passwordFieldConfirme;
    private javax.swing.JPasswordField passwordFieldSenha;
    private javax.swing.JTextField textFieldSenhaGerada;
    // End of variables declaration//GEN-END:variables
}
