/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.hibernate.HibernateUtil;
import org.hibernate.SessionFactory;

/**
 *
 * @author vandre
 */
public class dialogConexaoBD extends javax.swing.JDialog {
    
    private boolean conectado = false;
    
    /**
     * Creates new form dialogConexaoBD
     * @param parent
     * @param modal
     */
    public dialogConexaoBD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //já estabelecendo a conexao para agilizar o acesso posteriormente
                try {
                    SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
                    conectado = true;
                }
                finally {
                    setVisible(false);
                }
                
            }
        });        

        this.setVisible(true);
    }
    
    public boolean conectado() {
        return conectado;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConexaoBD = new javax.swing.JPanel();
        labelConexaoBD = new javax.swing.JLabel();
        labelImagemBD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 180));
        setUndecorated(true);
        setResizable(false);

        panelConexaoBD.setBackground(new java.awt.Color(254, 254, 254));
        panelConexaoBD.setMaximumSize(new java.awt.Dimension(350, 180));
        panelConexaoBD.setMinimumSize(new java.awt.Dimension(350, 180));
        panelConexaoBD.setPreferredSize(new java.awt.Dimension(350, 180));
        panelConexaoBD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelConexaoBD.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        labelConexaoBD.setText("Conectando ao Banco de Dados");
        panelConexaoBD.add(labelConexaoBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        labelImagemBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connect_database-100.png"))); // NOI18N
        panelConexaoBD.add(labelImagemBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelConexaoBD, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelConexaoBD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelConexaoBD;
    private javax.swing.JLabel labelImagemBD;
    private javax.swing.JPanel panelConexaoBD;
    // End of variables declaration//GEN-END:variables
}
