/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.controle.ControleExtrato;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Vandre
 */
public class panelExtrato extends javax.swing.JPanel implements Printable {
    
    final int MARGEM = 5;
    
    final private ControleExtrato controleExtrato;
    
    /**
     * Creates new form painelPreco
     */
    public panelExtrato() {
        initComponents();
        controleExtrato = new ControleExtrato(this);
    }
    
    public JTable getTabelaExtrato() {
        return tableExtrato; 
    }
    
    public JComboBox getComboBoxDentista() {
        return comboBoxDentista; 
    }

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if(pageIndex == 0) {
            Graphics2D grafico2d = (Graphics2D) graphics;
            grafico2d.scale(1, 1);
            grafico2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            
            printAll(grafico2d);
            return PAGE_EXISTS;
        }
        else {
            return NO_SUCH_PAGE;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneExtrato = new javax.swing.JScrollPane();
        tableExtrato = new javax.swing.JTable();
        comboBoxDentista = new javax.swing.JComboBox<>();
        labelFiltroDentista = new javax.swing.JLabel();
        labelImprimir = new javax.swing.JLabel();
        labelAbrir = new javax.swing.JLabel();
        labelFechar1 = new javax.swing.JLabel();
        labelLimpar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1270, 650));
        setMinimumSize(new java.awt.Dimension(1270, 650));
        setPreferredSize(new java.awt.Dimension(1270, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPaneExtrato.setOpaque(false);

        tableExtrato.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        tableExtrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Nº Orçamento", "Valor Orçamento", "Pagamento", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableExtrato.setMaximumSize(null);
        tableExtrato.setMinimumSize(null);
        tableExtrato.setOpaque(false);
        tableExtrato.setPreferredSize(null);
        tableExtrato.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableExtrato.getTableHeader().setReorderingAllowed(false);
        tableExtrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableExtratoMouseClicked(evt);
            }
        });
        scrollPaneExtrato.setViewportView(tableExtrato);

        add(scrollPaneExtrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 710, 410));

        comboBoxDentista.setEditable(true);
        comboBoxDentista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>" }));
        AutoCompleteDecorator.decorate(comboBoxDentista);
        comboBoxDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDentistaActionPerformed(evt);
            }
        });
        add(comboBoxDentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 35, 250, 25));

        labelFiltroDentista.setText("Filtrar por Dentista:");
        add(labelFiltroDentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        labelImprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImprimir.setText("Imprimir");
        labelImprimir.setMaximumSize(new java.awt.Dimension(90, 35));
        labelImprimir.setMinimumSize(new java.awt.Dimension(90, 35));
        labelImprimir.setOpaque(true);
        labelImprimir.setPreferredSize(new java.awt.Dimension(90, 35));
        labelImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImprimirMouseClicked(evt);
            }
        });
        add(labelImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, -1, -1));

        labelAbrir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAbrir.setText("Abrir");
        labelAbrir.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAbrir.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAbrir.setOpaque(true);
        labelAbrir.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAbrirMouseClicked(evt);
            }
        });
        add(labelAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, -1, -1));

        labelFechar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar1.setText("Fechar");
        labelFechar1.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar1.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar1.setOpaque(true);
        labelFechar1.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFechar1MouseClicked(evt);
            }
        });
        add(labelFechar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, -1, -1));

        labelLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLimpar.setText("Limpar");
        labelLimpar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelLimpar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelLimpar.setOpaque(true);
        labelLimpar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLimparMouseClicked(evt);
            }
        });
        add(labelLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDentistaActionPerformed
        if(controleExtrato != null)
            controleExtrato.PreencheTabelaExtrato();
    }//GEN-LAST:event_comboBoxDentistaActionPerformed

    private void tableExtratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableExtratoMouseClicked
        if (evt.getClickCount() == 2) {
            if(controleExtrato != null)
                controleExtrato.AbrirCadastro();
        }
    }//GEN-LAST:event_tableExtratoMouseClicked

    private void labelImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImprimirMouseClicked
        if(controleExtrato != null)
            controleExtrato.ImprimirExtrato();
    }//GEN-LAST:event_labelImprimirMouseClicked

    private void labelAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAbrirMouseClicked
        if(controleExtrato != null)
            controleExtrato.AbrirCadastro();
    }//GEN-LAST:event_labelAbrirMouseClicked

    private void labelFechar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFechar1MouseClicked
        if(controleExtrato != null)
            controleExtrato.Fechar();
    }//GEN-LAST:event_labelFechar1MouseClicked

    private void labelLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLimparMouseClicked
        comboBoxDentista.setSelectedIndex(0);
        ((DefaultTableModel)getTabelaExtrato().getModel()).setRowCount(0);
    }//GEN-LAST:event_labelLimparMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxDentista;
    private javax.swing.JLabel labelAbrir;
    private javax.swing.JLabel labelFechar1;
    private javax.swing.JLabel labelFiltroDentista;
    private javax.swing.JLabel labelImprimir;
    private javax.swing.JLabel labelLimpar;
    private javax.swing.JScrollPane scrollPaneExtrato;
    private javax.swing.JTable tableExtrato;
    // End of variables declaration//GEN-END:variables
}
