/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.controle.ControleListaPreco;
import com.vandremurakami.odousys.modelo.TabelaPreco;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JTable;

/**
 *
 * @author Vandre
 */
public class panelListarPreco extends javax.swing.JPanel {

    final private ControleListaPreco controlePreco;
    
    /**
     * Creates new form painelPreco
     * @param dialog
     * @param tabelaPreco
     */
    public panelListarPreco(JDialog dialog, TabelaPreco tabelaPreco) {
        initComponents();
        controlePreco = new ControleListaPreco(dialog, this, tabelaPreco);
        controlePreco.PreencheTabelaPreco();
    }
    
    public JTable getTabelaPreco() {
        return tablePreco; 
    }
    
    public String getFiltro() {
        return textFieldFiltro.getText().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanePreco = new javax.swing.JScrollPane();
        tablePreco = new javax.swing.JTable();
        labelAdicionar = new javax.swing.JLabel();
        labelAbrir = new javax.swing.JLabel();
        labelRemover = new javax.swing.JLabel();
        labelFechar = new javax.swing.JLabel();
        labelFiltro = new javax.swing.JLabel();
        textFieldFiltro = new javax.swing.JTextField();
        labelLimparFiltro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1060, 660));
        setMinimumSize(new java.awt.Dimension(1060, 660));
        setPreferredSize(new java.awt.Dimension(1060, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablePreco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePreco.setMaximumSize(null);
        tablePreco.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePreco.getTableHeader().setReorderingAllowed(false);
        tablePreco.getColumnModel().getColumn(0).setPreferredWidth(400);
        tablePreco.getColumnModel().getColumn(1).setPreferredWidth(100);
        tablePreco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePrecoMouseClicked(evt);
            }
        });
        scrollPanePreco.setViewportView(tablePreco);

        add(scrollPanePreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 800, 410));

        labelAdicionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdicionar.setText("Adicionar");
        labelAdicionar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAdicionar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAdicionar.setOpaque(true);
        labelAdicionar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAdicionarMouseClicked(evt);
            }
        });
        add(labelAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        labelAbrir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAbrir.setText("Abrir");
        labelAbrir.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAbrir.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAbrir.setOpaque(true);
        labelAbrir.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAbrirMouseClicked(evt);
            }
        });
        add(labelAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, -1, -1));

        labelRemover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRemover.setText("Remover");
        labelRemover.setMaximumSize(new java.awt.Dimension(90, 35));
        labelRemover.setMinimumSize(new java.awt.Dimension(90, 35));
        labelRemover.setOpaque(true);
        labelRemover.setPreferredSize(new java.awt.Dimension(90, 35));
        labelRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRemoverMouseClicked(evt);
            }
        });
        add(labelRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        labelFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar.setText("Fechar");
        labelFechar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar.setOpaque(true);
        labelFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharMouseClicked(evt);
            }
        });
        add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, -1, -1));

        labelFiltro.setText("Filtrar por nome:");
        add(labelFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        textFieldFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldFiltroKeyPressed(evt);
            }
        });
        add(textFieldFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 35, 250, 25));

        labelLimparFiltro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLimparFiltro.setText("Limpar");
        labelLimparFiltro.setMaximumSize(new java.awt.Dimension(90, 35));
        labelLimparFiltro.setMinimumSize(new java.awt.Dimension(90, 35));
        labelLimparFiltro.setOpaque(true);
        labelLimparFiltro.setPreferredSize(new java.awt.Dimension(90, 35));
        labelLimparFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLimparFiltroMouseClicked(evt);
            }
        });
        add(labelLimparFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tablePrecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePrecoMouseClicked
        if (evt.getClickCount() == 2) {
            if(controlePreco != null)
                controlePreco.CadastroAbrirPreco();
        }
    }//GEN-LAST:event_tablePrecoMouseClicked

    private void labelAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAdicionarMouseClicked
        if(controlePreco != null)
            controlePreco.CadastroAdicionarPreco();
    }//GEN-LAST:event_labelAdicionarMouseClicked

    private void labelAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAbrirMouseClicked
        if(controlePreco != null)
            controlePreco.CadastroAbrirPreco();
    }//GEN-LAST:event_labelAbrirMouseClicked

    private void labelRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRemoverMouseClicked
        if(controlePreco != null)
            controlePreco.RemovePreco();
    }//GEN-LAST:event_labelRemoverMouseClicked

    private void labelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharMouseClicked
        if(controlePreco != null)
            controlePreco.FecharListaPreco();
    }//GEN-LAST:event_labelFecharMouseClicked

    private void textFieldFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldFiltroKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if(controlePreco != null)
                controlePreco.PreencheTabelaPreco();
        }
    }//GEN-LAST:event_textFieldFiltroKeyPressed

    private void labelLimparFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLimparFiltroMouseClicked
        textFieldFiltro.setText("");
        if(controlePreco != null)
            controlePreco.PreencheTabelaPreco();
    }//GEN-LAST:event_labelLimparFiltroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAbrir;
    private javax.swing.JLabel labelAdicionar;
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelFiltro;
    private javax.swing.JLabel labelLimparFiltro;
    private javax.swing.JLabel labelRemover;
    private javax.swing.JScrollPane scrollPanePreco;
    private javax.swing.JTable tablePreco;
    private javax.swing.JTextField textFieldFiltro;
    // End of variables declaration//GEN-END:variables
}
