/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

/**
 *
 * @author vandre
 */
public class panelHome extends javax.swing.JPanel {

    /**
     * Creates new form panelHome
     */
    public panelHome() {
        initComponents();
        labelVersao.setText("Versão: " + getClass().getPackage().getImplementationVersion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelVersao = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 251, 254));
        setMaximumSize(new java.awt.Dimension(1260, 630));
        setMinimumSize(new java.awt.Dimension(1260, 630));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1260, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 380));

        labelVersao.setText("versão");
        add(labelVersao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 580, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelVersao;
    // End of variables declaration//GEN-END:variables
}
