/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.controle.ControleCadastroServicoOrcamento;
import com.vandremurakami.odousys.modelo.ServicoOrcamento;
import com.vandremurakami.odousys.modelo.TabelaPreco;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author vandre
 */
public class panelCadastroServicoOrcamento extends javax.swing.JPanel {

    
    private final ControleCadastroServicoOrcamento controleCadastroServicoOrcamento;
    
    /**
     * Creates new form panelCadastroAgenda
     * @param dialog
     * @param tabelaPreco
     * @param servicoOrcamento
     */
    public panelCadastroServicoOrcamento(JDialog dialog, TabelaPreco tabelaPreco ,ServicoOrcamento servicoOrcamento) {
        initComponents();
        controleCadastroServicoOrcamento = new ControleCadastroServicoOrcamento(dialog, this, tabelaPreco, servicoOrcamento);
    }
    
    public ServicoOrcamento getServicoOrcamento() {
        return controleCadastroServicoOrcamento.getServicoOrcamento();
    }
    
    public int getPosicaoServico() {
        //o primeiro elemento da combobox não é válido
        return comboBoxServico.getSelectedIndex()-1;
    }
    
    public void setNomeServico(String nome) {
        comboBoxServico.setSelectedItem(nome);
    }
    
    public int getQuantidade() {
        return comboBoxQuantidade.getSelectedIndex()+1;
    }
    
    public void setQuantidade(int quantidade) {
        comboBoxQuantidade.setSelectedIndex(quantidade-1);
    }

    public String getPorcentagemDescontoUnitario() {
        return textFieldPorcDescUnit.getText().trim();
    }
    
    public void setPorcentagemDescontoUnitario(String valor) {
        textFieldPorcDescUnit.setText(valor);
    }
    
    public String getDescontoUnitario() {
        return textFieldDescUnit.getText().trim();
    }
    
    public void setDescontoUnitario(String valor) {
        textFieldDescUnit.setText(valor);
    }
    
    public String getValorUnitario() {
        return textFieldValorUnitario.getText().trim();
    }
    
    public void setValorUnitario(String valor) {
        textFieldValorUnitario.setText(valor);
    }
    
    public String getObservacao() {
        return textAreaObservacao.getText().trim();
    }
    
    public void setObservacao(String obs) {
        textAreaObservacao.setText(obs);
    }
    
    public JComboBox getComboBoxServico() {
        return comboBoxServico;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAdicionar = new javax.swing.JLabel();
        labelFechar = new javax.swing.JLabel();
        labelServico = new javax.swing.JLabel();
        labelObservacao = new javax.swing.JLabel();
        comboBoxServico = new javax.swing.JComboBox<>();
        labelQuantidade = new javax.swing.JLabel();
        comboBoxQuantidade = new javax.swing.JComboBox<>();
        labelPorcDescUnit = new javax.swing.JLabel();
        textFieldPorcDescUnit = new javax.swing.JTextField();
        labelDescUnit = new javax.swing.JLabel();
        textFieldDescUnit = new javax.swing.JTextField();
        textFieldValorUnitario = new javax.swing.JTextField();
        labelValorUnitario = new javax.swing.JLabel();
        scrollPaneObservacao = new javax.swing.JScrollPane();
        textAreaObservacao = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1060, 660));
        setMinimumSize(new java.awt.Dimension(1060, 660));
        setPreferredSize(new java.awt.Dimension(1060, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAdicionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdicionar.setText("Adicionar");
        labelAdicionar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAdicionar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAdicionar.setOpaque(true);
        labelAdicionar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAdicionarMouseClicked(evt);
            }
        });
        add(labelAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        labelFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar.setText("Fechar");
        labelFechar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar.setOpaque(true);
        labelFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharMouseClicked(evt);
            }
        });
        add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        labelServico.setText("Serviço:");
        add(labelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 155, -1, -1));

        labelObservacao.setText("Observação:");
        add(labelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        comboBoxServico.setEditable(true);
        comboBoxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>" }));
        AutoCompleteDecorator.decorate(comboBoxServico);
        comboBoxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxServicoItemStateChanged(evt);
            }
        });
        add(comboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 420, 25));

        labelQuantidade.setText("Quantidade:");
        add(labelQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 205, -1, -1));

        comboBoxQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        AutoCompleteDecorator.decorate(comboBoxQuantidade);
        add(comboBoxQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 55, 25));

        labelPorcDescUnit.setText("Porc. Unit.:");
        add(labelPorcDescUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 255, -1, -1));

        textFieldPorcDescUnit.setText("0");
        textFieldPorcDescUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldPorcDescUnitKeyReleased(evt);
            }
        });
        add(textFieldPorcDescUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 55, 25));

        labelDescUnit.setText("Desc. Unit.:");
        add(labelDescUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 255, -1, -1));

        textFieldDescUnit.setText("0");
        textFieldDescUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldDescUnitKeyReleased(evt);
            }
        });
        add(textFieldDescUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 250, 80, 25));

        textFieldValorUnitario.setEditable(false);
        textFieldValorUnitario.setText("0");
        add(textFieldValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 250, 80, 25));

        labelValorUnitario.setText("Val. Unit.:");
        add(labelValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 255, -1, -1));

        textAreaObservacao.setColumns(20);
        textAreaObservacao.setRows(5);
        scrollPaneObservacao.setViewportView(textAreaObservacao);

        add(scrollPaneObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 420, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void labelAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAdicionarMouseClicked
        if(controleCadastroServicoOrcamento != null)
            controleCadastroServicoOrcamento.AdicionaAtualizaServicoOrcamento();
    }//GEN-LAST:event_labelAdicionarMouseClicked

    private void labelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharMouseClicked
        if(controleCadastroServicoOrcamento != null)
            controleCadastroServicoOrcamento.Fechar();
    }//GEN-LAST:event_labelFecharMouseClicked

    private void comboBoxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxServicoItemStateChanged
        if(controleCadastroServicoOrcamento != null)
            controleCadastroServicoOrcamento.setValorUnitario();
    }//GEN-LAST:event_comboBoxServicoItemStateChanged

    private void textFieldDescUnitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldDescUnitKeyReleased
       if(controleCadastroServicoOrcamento != null)
            controleCadastroServicoOrcamento.setValorDesconto();
    }//GEN-LAST:event_textFieldDescUnitKeyReleased

    private void textFieldPorcDescUnitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldPorcDescUnitKeyReleased
        if(controleCadastroServicoOrcamento != null)
            controleCadastroServicoOrcamento.setPorcentagemDesconto();
    }//GEN-LAST:event_textFieldPorcDescUnitKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxQuantidade;
    private javax.swing.JComboBox<String> comboBoxServico;
    private javax.swing.JLabel labelAdicionar;
    private javax.swing.JLabel labelDescUnit;
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelObservacao;
    private javax.swing.JLabel labelPorcDescUnit;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelServico;
    private javax.swing.JLabel labelValorUnitario;
    private javax.swing.JScrollPane scrollPaneObservacao;
    private javax.swing.JTextArea textAreaObservacao;
    private javax.swing.JTextField textFieldDescUnit;
    private javax.swing.JTextField textFieldPorcDescUnit;
    private javax.swing.JTextField textFieldValorUnitario;
    // End of variables declaration//GEN-END:variables
}
