/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.controle.ControleRelatorioMensal;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author vandr
 */
public class panelFaturamentoMensal extends javax.swing.JPanel {

    private final ControleRelatorioMensal controleRelatorioMensal = new ControleRelatorioMensal();
    
    /**
     * Creates new form painelFaturamentoMensal
     */
    public panelFaturamentoMensal() {
        initComponents();
        criaGraficoBarras();
    }
    
    private void criaGraficoBarras() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        int ano = LocalDate.now().getYear();
                
        controleRelatorioMensal.setData(1, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Jan");
        
        controleRelatorioMensal.setData(2, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Fev");
        
        controleRelatorioMensal.setData(3, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Mar");
        
        controleRelatorioMensal.setData(4, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Abr");
        
        controleRelatorioMensal.setData(5, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Mai");
        
        controleRelatorioMensal.setData(6, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Jun");

        controleRelatorioMensal.setData(7, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Jul");
        
        controleRelatorioMensal.setData(8, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Ago");
        
        controleRelatorioMensal.setData(9, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Set");
        
        controleRelatorioMensal.setData(10, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Out");
        
        controleRelatorioMensal.setData(11, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Nov");
        
        controleRelatorioMensal.setData(12, ano);
        dataset.setValue(controleRelatorioMensal.valorTotal(), "Reais", "Dez");
        
        JFreeChart barchart = ChartFactory.createBarChart("", "Meses", "Reais", dataset, PlotOrientation.VERTICAL, false, true, false);
        
        CategoryPlot bar = barchart.getCategoryPlot();
        bar.setRangeGridlinePaint(Color.ORANGE);
        
        ChartPanel barPanel = new ChartPanel(barchart);
        barPanel.setSize(1260, 670);
        
        this.add(barPanel, BorderLayout.CENTER);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1260, 670));
        setMinimumSize(new java.awt.Dimension(1260, 670));
        setPreferredSize(new java.awt.Dimension(1260, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
