/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.controle.ControleCadastroUsuario;
import com.vandremurakami.odousys.modelo.Usuario;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author vandre
 */
public class panelCadastroUsuario extends javax.swing.JPanel {

    final private ControleCadastroUsuario controleCadastroUsuario;

    private String senhaOriginal = "";
    
    /**
     * Creates new form panelUsuario
     * @param dialog
     * @param usuario
     */
    public panelCadastroUsuario(JDialog dialog, Usuario usuario) {
        initComponents();
        controleCadastroUsuario = new ControleCadastroUsuario(dialog, this, usuario);
    }
    
    public void setNomeDentista(String nome) {
        comboBoxDentista.setSelectedItem(nome);
    }
    
    public int getPosicaoDentista() {
        return comboBoxDentista.getSelectedIndex()-1;
    }
    
    public JComboBox getComboBoxDentista() {
        return comboBoxDentista;
    }
    
    public String getLogin() {
        return textFieldLogin.getText().trim();
    }

    public void setLogin(String login) {
        textFieldLogin.setText(login);
    }
    
    public String getSenha() {
        return passwordField.getText();
    }
    
    public void setSenha(String password) {
        senhaOriginal = password;
        passwordField.setText(password);
    }

    public boolean senhaAlterada() {
        return (!senhaOriginal.equals(passwordField.getText()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDentista = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        labelSalvar = new javax.swing.JLabel();
        labelFechar = new javax.swing.JLabel();
        textFieldLogin = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        comboBoxDentista = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setPreferredSize(new java.awt.Dimension(1024, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDentista.setText("Dentista:");
        add(labelDentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        labelLogin.setText("Login:");
        add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        labelSenha.setText("Senha:");
        add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        labelSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSalvar.setText("Salvar");
        labelSalvar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelSalvar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelSalvar.setOpaque(true);
        labelSalvar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSalvarMouseClicked(evt);
            }
        });
        add(labelSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        labelFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar.setText("Fechar");
        labelFechar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar.setOpaque(true);
        labelFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharMouseClicked(evt);
            }
        });
        add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        textFieldLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldLoginKeyPressed(evt);
            }
        });
        add(textFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 185, 330, 25));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 285, 330, 25));

        comboBoxDentista.setEditable(true);
        comboBoxDentista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>" }));
        AutoCompleteDecorator.decorate(comboBoxDentista);
        add(comboBoxDentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 235, 250, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void labelSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalvarMouseClicked
        controleCadastroUsuario.AdicionaAtualizaUsuario();
    }//GEN-LAST:event_labelSalvarMouseClicked

    private void labelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharMouseClicked
        controleCadastroUsuario.Fechar();
    }//GEN-LAST:event_labelFecharMouseClicked

    private void textFieldLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldLoginKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            passwordField.requestFocus();
        }
    }//GEN-LAST:event_textFieldLoginKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxDentista;
    private javax.swing.JLabel labelDentista;
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSalvar;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField textFieldLogin;
    // End of variables declaration//GEN-END:variables
}
