/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.controle.ControleCadastroOrcamento;
import com.vandremurakami.odousys.modelo.Orcamento;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JTable;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author vandre
 */
public class panelCadastroOrcamento extends javax.swing.JPanel {

    private final ControleCadastroOrcamento controleCadastroOrcamento;
    
    /**
     * Creates new form panelCadastroOrcamento
     * @param dialog
     * @param orcamento
     */
    public panelCadastroOrcamento(JDialog dialog, Orcamento orcamento) {
        initComponents();
        controleCadastroOrcamento = new ControleCadastroOrcamento(dialog, this, orcamento);
    }
    
    public void setNomeDentista(String nome) {
        comboBoxDentista.setSelectedItem(nome);
    }
    
    public int getPosicaoDentista() {
        return comboBoxDentista.getSelectedIndex()-1;
    }
    
    public void setPaciente(String paciente) {
        textFieldPaciente.setText(paciente);
    }
    
    public String getPaciente() {
        return textFieldPaciente.getText().trim();
    }
    
    public void setNomeStatus(String nome) {
        comboBoxStatus.setSelectedItem(nome);
    }
    
    public int getPosicaoStatus() {
        return comboBoxStatus.getSelectedIndex()-1;
    }

    public void setPorcentagemDesconto(String porc) {
        textFieldPorcentagemDesconto.setText(porc);
    }
    
    public String getPorcentagemDesconto() {
        return textFieldPorcentagemDesconto.getText().trim();
    }
    
    public void setValorDesconto(String valor) {
        textFieldValorDesconto.setText(valor);
    }
    
    public String getValorDesconto() {
        return textFieldValorDesconto.getText().trim();
    }
    
    public void setValorFinal(String valor) {
        textFieldValorFinal.setText(valor);
    }
    
    public String getValorFinal() {
        return textFieldValorFinal.getText().trim();
    }
    
    public void setObservacao(String obs) {
        textPaneObservacao.setText(obs);
    }
    
    public String getObservacao() {
        return textPaneObservacao.getText().trim();
    }
    
    public JTable getTabelaServicos() {
        return tableServicos;
    }
    
    public JComboBox getComboBoxDentista() {
        return comboBoxDentista;
    }
    
    public JComboBox getComboBoxStatus() {
        return comboBoxStatus;
    }
    
    public void setTabelaPreco(String nome) {
        labelTabelaPreco.setText(nome);
    }
    
    public void setNaoEditavel() {
        labelAdicionar.setVisible(false);
        labelAbrir.setVisible(false);
        labelRemover.setVisible(false);
        tableServicos.setEnabled(false);
        textFieldPaciente.setEnabled(false);
        textFieldPorcentagemDesconto.setEnabled(false);
        textFieldValorDesconto.setEnabled(false);
        textPaneObservacao.setEnabled(false);
        comboBoxDentista.setEnabled(false);
    }
    
    public void setEditavel() {
        labelAdicionar.setVisible(true);
        labelAbrir.setVisible(true);
        labelRemover.setVisible(true);
        tableServicos.setEnabled(true);
        textFieldPaciente.setEnabled(true);
        textFieldPorcentagemDesconto.setEnabled(true);
        textFieldValorDesconto.setEnabled(true);
        textPaneObservacao.setEnabled(true);
        comboBoxDentista.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSalvar = new javax.swing.JLabel();
        labelFechar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldPorcentagemDesconto = new javax.swing.JTextField();
        textFieldValorDesconto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textFieldValorFinal = new javax.swing.JTextField();
        comboBoxDentista = new javax.swing.JComboBox<>();
        scrollPaneServico = new javax.swing.JScrollPane();
        tableServicos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        comboBoxStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        textFieldPaciente = new javax.swing.JTextField();
        scrollPaneObservacao = new javax.swing.JScrollPane();
        textPaneObservacao = new javax.swing.JTextPane();
        labelAdicionar = new javax.swing.JLabel();
        labelAbrir = new javax.swing.JLabel();
        labelRemover = new javax.swing.JLabel();
        labelImprimirOrcamento = new javax.swing.JLabel();
        labelTabelaPreco = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1060, 660));
        setMinimumSize(new java.awt.Dimension(1060, 660));
        setPreferredSize(new java.awt.Dimension(1060, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSalvar.setText("Salvar");
        labelSalvar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelSalvar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelSalvar.setOpaque(true);
        labelSalvar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSalvarMouseClicked(evt);
            }
        });
        add(labelSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, -1, -1));

        labelFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar.setText("Fechar");
        labelFechar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar.setOpaque(true);
        labelFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharMouseClicked(evt);
            }
        });
        add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, -1, -1));

        jLabel1.setText("Dentista:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 45, -1, -1));

        jLabel5.setText("Porcentagem de Desconto:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 405, -1, -1));

        jLabel6.setText("Valor do Desconto:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 405, -1, -1));

        textFieldPorcentagemDesconto.setText("0");
        textFieldPorcentagemDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldPorcentagemDescontoKeyReleased(evt);
            }
        });
        add(textFieldPorcentagemDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 55, 25));

        textFieldValorDesconto.setText("0");
        textFieldValorDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldValorDescontoKeyReleased(evt);
            }
        });
        add(textFieldValorDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 80, 25));

        jLabel8.setText("Valor Final:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 405, -1, -1));

        textFieldValorFinal.setEditable(false);
        textFieldValorFinal.setText("0");
        add(textFieldValorFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 80, 25));

        comboBoxDentista.setEditable(true);
        comboBoxDentista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>" }));
        AutoCompleteDecorator.decorate(comboBoxDentista);
        add(comboBoxDentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 250, 25));

        tableServicos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serviço", "Preço", "Desc.", "Qtd", "Observação", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableServicos.setMaximumSize(null);
        tableServicos.setMinimumSize(null);
        tableServicos.setPreferredSize(null);
        tableServicos.getTableHeader().setReorderingAllowed(false);
        tableServicos.getColumnModel().getColumn(0).setPreferredWidth(250);
        tableServicos.getColumnModel().getColumn(1).setPreferredWidth(17);
        tableServicos.getColumnModel().getColumn(2).setPreferredWidth(17);
        tableServicos.getColumnModel().getColumn(3).setPreferredWidth(5);
        tableServicos.getColumnModel().getColumn(4).setPreferredWidth(120);
        tableServicos.getColumnModel().getColumn(5).setPreferredWidth(23);
        tableServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableServicosMouseClicked(evt);
            }
        });
        scrollPaneServico.setViewportView(tableServicos);

        add(scrollPaneServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 800, 150));

        jLabel2.setText("Status:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 45, -1, -1));

        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>" }));
        AutoCompleteDecorator.decorate(comboBoxStatus);
        comboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxStatusActionPerformed(evt);
            }
        });
        add(comboBoxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 250, 25));

        jLabel4.setText("Paciente:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 95, -1, -1));
        add(textFieldPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 250, 25));

        scrollPaneObservacao.setBorder(null);

        textPaneObservacao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Observação"));
        scrollPaneObservacao.setViewportView(textPaneObservacao);

        add(scrollPaneObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 500, 110));

        labelAdicionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdicionar.setText("Adicionar");
        labelAdicionar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAdicionar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAdicionar.setOpaque(true);
        labelAdicionar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAdicionarMouseClicked(evt);
            }
        });
        add(labelAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        labelAbrir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAbrir.setText("Abrir");
        labelAbrir.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAbrir.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAbrir.setOpaque(true);
        labelAbrir.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAbrirMouseClicked(evt);
            }
        });
        add(labelAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        labelRemover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRemover.setText("Remover");
        labelRemover.setMaximumSize(new java.awt.Dimension(90, 35));
        labelRemover.setMinimumSize(new java.awt.Dimension(90, 35));
        labelRemover.setOpaque(true);
        labelRemover.setPreferredSize(new java.awt.Dimension(90, 35));
        labelRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRemoverMouseClicked(evt);
            }
        });
        add(labelRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        labelImprimirOrcamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImprimirOrcamento.setText("Imprimir");
        labelImprimirOrcamento.setMaximumSize(new java.awt.Dimension(90, 35));
        labelImprimirOrcamento.setMinimumSize(new java.awt.Dimension(90, 35));
        labelImprimirOrcamento.setOpaque(true);
        labelImprimirOrcamento.setPreferredSize(new java.awt.Dimension(90, 35));
        labelImprimirOrcamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImprimirOrcamentoMouseClicked(evt);
            }
        });
        add(labelImprimirOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, -1, -1));

        labelTabelaPreco.setText("Tabela de Preco");
        add(labelTabelaPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void labelSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalvarMouseClicked
        if(controleCadastroOrcamento != null)
            controleCadastroOrcamento.AdicionaAtualizaOrcamento();
    }//GEN-LAST:event_labelSalvarMouseClicked

    private void labelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharMouseClicked
        if(controleCadastroOrcamento != null)
            controleCadastroOrcamento.Fechar();
    }//GEN-LAST:event_labelFecharMouseClicked

    private void tableServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableServicosMouseClicked
        if (evt.getClickCount() == 2) {
            if(controleCadastroOrcamento != null)
                controleCadastroOrcamento.CadastroAbrirServico();
        }
    }//GEN-LAST:event_tableServicosMouseClicked

    private void labelAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAdicionarMouseClicked
        if(controleCadastroOrcamento != null)
            controleCadastroOrcamento.CadastroAdicionarServico();
    }//GEN-LAST:event_labelAdicionarMouseClicked

    private void labelAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAbrirMouseClicked
        if(controleCadastroOrcamento != null)
            controleCadastroOrcamento.CadastroAbrirServico();
    }//GEN-LAST:event_labelAbrirMouseClicked

    private void labelRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRemoverMouseClicked
        if(controleCadastroOrcamento != null)
            controleCadastroOrcamento.RemoverServico();
    }//GEN-LAST:event_labelRemoverMouseClicked

    private void labelImprimirOrcamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImprimirOrcamentoMouseClicked
        if(controleCadastroOrcamento != null)
            controleCadastroOrcamento.ImprimirOrcamento();
    }//GEN-LAST:event_labelImprimirOrcamentoMouseClicked

    private void comboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxStatusActionPerformed
        if(controleCadastroOrcamento != null)
            controleCadastroOrcamento.ConfiguraStatus();
    }//GEN-LAST:event_comboBoxStatusActionPerformed

    private void textFieldValorDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldValorDescontoKeyReleased
        if(controleCadastroOrcamento != null)
            controleCadastroOrcamento.setValorDesconto();
    }//GEN-LAST:event_textFieldValorDescontoKeyReleased

    private void textFieldPorcentagemDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldPorcentagemDescontoKeyReleased
        if(controleCadastroOrcamento != null)
            controleCadastroOrcamento.setPorcentagemDesconto();
    }//GEN-LAST:event_textFieldPorcentagemDescontoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxDentista;
    private javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelAbrir;
    private javax.swing.JLabel labelAdicionar;
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelImprimirOrcamento;
    private javax.swing.JLabel labelRemover;
    private javax.swing.JLabel labelSalvar;
    private javax.swing.JLabel labelTabelaPreco;
    private javax.swing.JScrollPane scrollPaneObservacao;
    private javax.swing.JScrollPane scrollPaneServico;
    private javax.swing.JTable tableServicos;
    private javax.swing.JTextField textFieldPaciente;
    private javax.swing.JTextField textFieldPorcentagemDesconto;
    private javax.swing.JTextField textFieldValorDesconto;
    private javax.swing.JTextField textFieldValorFinal;
    private javax.swing.JTextPane textPaneObservacao;
    // End of variables declaration//GEN-END:variables

}
