/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.controle.ControleListaAgenda;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.JTable;

/**
 *
 * @author Vandre
 */
public class panelListarAgenda extends javax.swing.JPanel {

    private final ControleListaAgenda controleListaAgenda;
    
    /**
     * Creates new form painelListarAgenda
     */
    public panelListarAgenda() {
        initComponents();
        controleListaAgenda = new ControleListaAgenda(this);
    }
    
    public JTable getTabelaAgenda() {
        return tableAgenda; 
    }
    
    public LocalDate getData() {
        if(calendar.getDate() != null)
            return calendar.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        else
            return null;
    }
    
    public void setData(LocalDate data) {
        calendar.setDate(Date.from(data.atStartOfDay(ZoneId.systemDefault()).toInstant()));
    }
    
    CellEditorListener ChangeNotification = new CellEditorListener() {
        @Override
        public void editingStopped(ChangeEvent e) {
            controleListaAgenda.checkAgenda();
        }

        @Override
        public void editingCanceled(ChangeEvent e) {
            //Quando uma célula que começou a aditar foi cancelada com ESC
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneAgenda = new javax.swing.JScrollPane();
        tableAgenda = new javax.swing.JTable();
        labelAdicionar = new javax.swing.JLabel();
        labelAbrir = new javax.swing.JLabel();
        labelFechar = new javax.swing.JLabel();
        labelRemover = new javax.swing.JLabel();
        labelAnterior = new javax.swing.JLabel();
        labelProximo = new javax.swing.JLabel();
        labelHoje = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JCalendar();

        setBackground(new java.awt.Color(254, 254, 254));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(1260, 630));
        setMinimumSize(new java.awt.Dimension(1260, 630));
        setPreferredSize(new java.awt.Dimension(1260, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPaneAgenda.setMaximumSize(new java.awt.Dimension(1085, 410));
        scrollPaneAgenda.setMinimumSize(new java.awt.Dimension(1085, 410));
        scrollPaneAgenda.setPreferredSize(new java.awt.Dimension(1085, 410));

        tableAgenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Dentista", "Anotação", "Check"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAgenda.setMaximumSize(null);
        tableAgenda.setMinimumSize(null);
        tableAgenda.setPreferredSize(null);
        tableAgenda.setRowHeight(22);
        tableAgenda.getColumnModel().getColumn(0).setPreferredWidth(60);
        tableAgenda.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableAgenda.getColumnModel().getColumn(2).setPreferredWidth(520);
        tableAgenda.getColumnModel().getColumn(3).setPreferredWidth(60);
        tableAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAgendaMouseClicked(evt);
            }
        });
        tableAgenda.getDefaultEditor(Boolean.class).addCellEditorListener(ChangeNotification);
        scrollPaneAgenda.setViewportView(tableAgenda);

        add(scrollPaneAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 60, 850, 500));

        labelAdicionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdicionar.setText("Adicionar");
        labelAdicionar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAdicionar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAdicionar.setOpaque(true);
        labelAdicionar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAdicionarMouseClicked(evt);
            }
        });
        add(labelAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 310, -1));

        labelAbrir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAbrir.setText("Abrir");
        labelAbrir.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAbrir.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAbrir.setOpaque(true);
        labelAbrir.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAbrirMouseClicked(evt);
            }
        });
        add(labelAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 310, -1));

        labelFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar.setText("Fechar");
        labelFechar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar.setOpaque(true);
        labelFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharMouseClicked(evt);
            }
        });
        add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 310, -1));

        labelRemover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRemover.setText("Remover");
        labelRemover.setMaximumSize(new java.awt.Dimension(90, 35));
        labelRemover.setMinimumSize(new java.awt.Dimension(90, 35));
        labelRemover.setOpaque(true);
        labelRemover.setPreferredSize(new java.awt.Dimension(90, 35));
        labelRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRemoverMouseClicked(evt);
            }
        });
        add(labelRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 310, -1));

        labelAnterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAnterior.setText("Anterior");
        labelAnterior.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAnterior.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAnterior.setOpaque(true);
        labelAnterior.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAnteriorMouseClicked(evt);
            }
        });
        add(labelAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        labelProximo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProximo.setText("Próximo");
        labelProximo.setMaximumSize(new java.awt.Dimension(90, 35));
        labelProximo.setMinimumSize(new java.awt.Dimension(90, 35));
        labelProximo.setOpaque(true);
        labelProximo.setPreferredSize(new java.awt.Dimension(90, 35));
        labelProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelProximoMouseClicked(evt);
            }
        });
        add(labelProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        labelHoje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHoje.setText("Hoje");
        labelHoje.setMaximumSize(new java.awt.Dimension(90, 35));
        labelHoje.setMinimumSize(new java.awt.Dimension(90, 35));
        labelHoje.setOpaque(true);
        labelHoje.setPreferredSize(new java.awt.Dimension(90, 35));
        labelHoje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHojeMouseClicked(evt);
            }
        });
        add(labelHoje, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        calendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendarPropertyChange(evt);
            }
        });
        add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 310, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void tableAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAgendaMouseClicked
        if (evt.getClickCount() == 2) {
            if(controleListaAgenda != null)
                controleListaAgenda.CadastroAbrirAgenda();
        }
    }//GEN-LAST:event_tableAgendaMouseClicked

    private void labelAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAdicionarMouseClicked
        if(controleListaAgenda != null)
            controleListaAgenda.CadastroAdicionarAgenda();
    }//GEN-LAST:event_labelAdicionarMouseClicked

    private void labelAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAbrirMouseClicked
        if(controleListaAgenda != null)
            controleListaAgenda.CadastroAbrirAgenda();
    }//GEN-LAST:event_labelAbrirMouseClicked

    private void labelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharMouseClicked
        if(controleListaAgenda != null)
            controleListaAgenda.FecharListaAgenda();
    }//GEN-LAST:event_labelFecharMouseClicked

    private void labelRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRemoverMouseClicked
        if(controleListaAgenda != null)
            controleListaAgenda.RemoveListaAgenda();
    }//GEN-LAST:event_labelRemoverMouseClicked

    private void labelAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAnteriorMouseClicked
        if(controleListaAgenda != null)
            controleListaAgenda.anteriorDia();
    }//GEN-LAST:event_labelAnteriorMouseClicked

    private void labelProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelProximoMouseClicked
        if(controleListaAgenda != null)
            controleListaAgenda.proximoDia();
    }//GEN-LAST:event_labelProximoMouseClicked

    private void labelHojeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHojeMouseClicked
        if(controleListaAgenda != null)
            controleListaAgenda.hojeDia();
    }//GEN-LAST:event_labelHojeMouseClicked

    private void calendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendarPropertyChange
        if(controleListaAgenda != null)
            controleListaAgenda.PreencheTabelaAgenda();
    }//GEN-LAST:event_calendarPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JLabel labelAbrir;
    private javax.swing.JLabel labelAdicionar;
    private javax.swing.JLabel labelAnterior;
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelHoje;
    private javax.swing.JLabel labelProximo;
    private javax.swing.JLabel labelRemover;
    private javax.swing.JScrollPane scrollPaneAgenda;
    private javax.swing.JTable tableAgenda;
    // End of variables declaration//GEN-END:variables
}
