/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.controle.ControleListaUsuario;
import java.awt.event.KeyEvent;
import javax.swing.JTable;

/**
 *
 * @author vandre
 */
public class panelListarUsuario extends javax.swing.JPanel {
    
    final private ControleListaUsuario controleListaUsuario;
    
    /**
     * Creates new form panelUsuario
     */
    public panelListarUsuario() {
        initComponents();
        controleListaUsuario = new ControleListaUsuario(this);
    }

    public JTable getTabelaUsuarios() {
        return tableUsuarios; 
    }
    
    public String getFiltro() {
        return textFieldFiltro.getText().trim();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneTabelaUsuarios = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        labelFiltro1 = new javax.swing.JLabel();
        textFieldFiltro = new javax.swing.JTextField();
        labelLimparFiltro = new javax.swing.JLabel();
        labelAdicionar1 = new javax.swing.JLabel();
        labelAbrir1 = new javax.swing.JLabel();
        labelRemover1 = new javax.swing.JLabel();
        labelFechar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1260, 630));
        setMinimumSize(new java.awt.Dimension(1260, 630));
        setPreferredSize(new java.awt.Dimension(1260, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPaneTabelaUsuarios.setBackground(new java.awt.Color(254, 254, 254));
        scrollPaneTabelaUsuarios.setMaximumSize(null);
        scrollPaneTabelaUsuarios.setMinimumSize(null);

        tableUsuarios.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login", "Dentista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUsuariosMouseClicked(evt);
            }
        });
        scrollPaneTabelaUsuarios.setViewportView(tableUsuarios);

        add(scrollPaneTabelaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 710, 410));

        labelFiltro1.setText("Filtrar por login:");
        add(labelFiltro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        textFieldFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldFiltroKeyPressed(evt);
            }
        });
        add(textFieldFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 35, 250, 25));

        labelLimparFiltro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLimparFiltro.setText("Limpar");
        labelLimparFiltro.setMaximumSize(new java.awt.Dimension(90, 35));
        labelLimparFiltro.setMinimumSize(new java.awt.Dimension(90, 35));
        labelLimparFiltro.setOpaque(true);
        labelLimparFiltro.setPreferredSize(new java.awt.Dimension(90, 35));
        labelLimparFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLimparFiltroMouseClicked(evt);
            }
        });
        add(labelLimparFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        labelAdicionar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdicionar1.setText("Adicionar");
        labelAdicionar1.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAdicionar1.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAdicionar1.setOpaque(true);
        labelAdicionar1.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAdicionar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAdicionar1MouseClicked(evt);
            }
        });
        add(labelAdicionar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, -1, -1));

        labelAbrir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAbrir1.setText("Abrir");
        labelAbrir1.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAbrir1.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAbrir1.setOpaque(true);
        labelAbrir1.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAbrir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAbrir1MouseClicked(evt);
            }
        });
        add(labelAbrir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, -1));

        labelRemover1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRemover1.setText("Remover");
        labelRemover1.setMaximumSize(new java.awt.Dimension(90, 35));
        labelRemover1.setMinimumSize(new java.awt.Dimension(90, 35));
        labelRemover1.setOpaque(true);
        labelRemover1.setPreferredSize(new java.awt.Dimension(90, 35));
        labelRemover1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRemover1MouseClicked(evt);
            }
        });
        add(labelRemover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, -1, -1));

        labelFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar.setText("Fechar");
        labelFechar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar.setOpaque(true);
        labelFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharMouseClicked(evt);
            }
        });
        add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuariosMouseClicked
        if (evt.getClickCount() == 2) {
            controleListaUsuario.CadastroAbrirUsuario();
        }
    }//GEN-LAST:event_tableUsuariosMouseClicked

    private void textFieldFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldFiltroKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if(controleListaUsuario != null)
            controleListaUsuario.PreencheTabelaUsuario();
        }
    }//GEN-LAST:event_textFieldFiltroKeyPressed

    private void labelLimparFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLimparFiltroMouseClicked
        textFieldFiltro.setText("");
        if(controleListaUsuario != null)
            controleListaUsuario.PreencheTabelaUsuario();
    }//GEN-LAST:event_labelLimparFiltroMouseClicked

    private void labelAdicionar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAdicionar1MouseClicked
        if(controleListaUsuario != null)
            controleListaUsuario.CadastroAdicionarUsuario();
    }//GEN-LAST:event_labelAdicionar1MouseClicked

    private void labelAbrir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAbrir1MouseClicked
        if(controleListaUsuario != null)
            controleListaUsuario.CadastroAbrirUsuario();
    }//GEN-LAST:event_labelAbrir1MouseClicked

    private void labelRemover1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRemover1MouseClicked
        if(controleListaUsuario != null)
            controleListaUsuario.RemoveUsuario();
    }//GEN-LAST:event_labelRemover1MouseClicked

    private void labelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharMouseClicked
        if(controleListaUsuario != null)
            controleListaUsuario.FecharListaDentista();
    }//GEN-LAST:event_labelFecharMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAbrir1;
    private javax.swing.JLabel labelAdicionar1;
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelFiltro1;
    private javax.swing.JLabel labelLimparFiltro;
    private javax.swing.JLabel labelRemover1;
    private javax.swing.JScrollPane scrollPaneTabelaUsuarios;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JTextField textFieldFiltro;
    // End of variables declaration//GEN-END:variables
}
