/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.controle.ControleCadastroPagamento;
import com.vandremurakami.odousys.modelo.Pagamento;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author vandre
 */
public class panelCadastroPagamento extends javax.swing.JPanel {

    
    private final ControleCadastroPagamento controleCadastroPagamento;
    
    /**
     * Creates new form panelCadastroPagemento
     * @param dialog
     * @param pagamento
     */
    public panelCadastroPagamento(JDialog dialog, Pagamento pagamento) {
        initComponents();
        controleCadastroPagamento = new ControleCadastroPagamento(dialog, this, pagamento);
    }
    
    public int getPosicaoStatus() {
        //o primeiro elemento da combobox não é válido
        return comboBoxStatus.getSelectedIndex()-1;
    }
    
    public void setNomeStatus(String nome) {
        comboBoxStatus.setSelectedItem(nome);
    }
    
    public int getPosicaoDentista() {
        //o primeiro elemento da combobox não é válido
        return comboBoxDentista.getSelectedIndex()-1;
    }
    
    public void setNomeDentista(String nome) {
        comboBoxDentista.setSelectedItem(nome);
    }
    
    public int getPosicaoTipoPagamento() {
        //o primeiro elemento da combobox não é válido
        return comboBoxTipoPagamento.getSelectedIndex()-1;
    }
    
    public void setNomeTipoPagamento(String nome) {
        comboBoxTipoPagamento.setSelectedItem(nome);
    }
    
    public LocalDate getDataPagamento() {
        if (dateChooser.getDate() != null)
            return dateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        else
            return null;
    }
    
    public void setDataPagamento(LocalDate data) {
        dateChooser.setDate(Date.from(data.atStartOfDay(ZoneId.systemDefault()).toInstant()));
    }
    
    public String getValor() {
        return textFieldValor.getText().trim();
    }
    
    public void setValor(String valor) {
        textFieldValor.setText(valor);
    }
    
    public String getObservacao() {
        return textAreaObservacao.getText().trim();
    }
    
    public void setObservacao(String obs) {
        textAreaObservacao.setText(obs);
    }
    
    public JComboBox getComboBoxDentista() {
        return comboBoxDentista;
    }
    
    public JComboBox getComboBoxStatus() {
        return comboBoxStatus;
    }
    
    public JComboBox getComboBoxTipoPagamento() {
        return comboBoxTipoPagamento;
    }
    
    public void setNaoEditavel() {
        dateChooser.setEnabled(false);
        comboBoxDentista.setEnabled(false);
        textFieldValor.setEnabled(false);
        textFieldValor.setEnabled(false);
        comboBoxTipoPagamento.setEnabled(false);
        textAreaObservacao.setEnabled(false);
    }
    
    public void setEditavel() {
        dateChooser.setEnabled(true);
        comboBoxDentista.setEnabled(true);
        textFieldValor.setEnabled(true);
        textFieldValor.setEnabled(true);
        comboBoxTipoPagamento.setEnabled(true);
        textAreaObservacao.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSalvar = new javax.swing.JLabel();
        labelFechar = new javax.swing.JLabel();
        labelDentista = new javax.swing.JLabel();
        comboBoxStatus = new javax.swing.JComboBox<>();
        comboBoxDentista = new javax.swing.JComboBox<>();
        labelStatus = new javax.swing.JLabel();
        comboBoxTipoPagamento = new javax.swing.JComboBox<>();
        labelObservacao = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        textFieldValor = new javax.swing.JTextField();
        labelData = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        labelTipoPagamento = new javax.swing.JLabel();
        scrollPaneObservacao = new javax.swing.JScrollPane();
        textAreaObservacao = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1060, 660));
        setMinimumSize(new java.awt.Dimension(1060, 660));
        setPreferredSize(new java.awt.Dimension(1060, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSalvar.setText("Salvar");
        labelSalvar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelSalvar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelSalvar.setOpaque(true);
        labelSalvar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSalvarMouseClicked(evt);
            }
        });
        add(labelSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        labelFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar.setText("Fechar");
        labelFechar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar.setOpaque(true);
        labelFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharMouseClicked(evt);
            }
        });
        add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        labelDentista.setText("Dentista:");
        add(labelDentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 155, -1, -1));

        comboBoxStatus.setEditable(true);
        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>" }));
        AutoCompleteDecorator.decorate(comboBoxStatus);
        comboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxStatusActionPerformed(evt);
            }
        });
        add(comboBoxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 250, 25));

        comboBoxDentista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>" }));
        AutoCompleteDecorator.decorate(comboBoxDentista);
        add(comboBoxDentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 250, 25));

        labelStatus.setText("Status:");
        add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 155, -1, -1));

        comboBoxTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione uma das opções>" }));
        AutoCompleteDecorator.decorate(comboBoxTipoPagamento);
        add(comboBoxTipoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 25));

        labelObservacao.setText("Observação:");
        add(labelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        labelValor.setText("Valor:");
        add(labelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 205, -1, -1));
        add(textFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 250, 25));

        labelData.setText("Data:");
        add(labelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 205, -1, -1));

        dateChooser.setMaximumSize(null);
        dateChooser.setMinimumSize(null);
        add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 250, 25));

        labelTipoPagamento.setText("Tipo de Pagamento:");
        add(labelTipoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 255, -1, -1));

        textAreaObservacao.setColumns(20);
        textAreaObservacao.setRows(5);
        scrollPaneObservacao.setViewportView(textAreaObservacao);

        add(scrollPaneObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 570, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void labelSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalvarMouseClicked
        if(controleCadastroPagamento != null)
            controleCadastroPagamento.AdicionaAtualizaPagamento();
    }//GEN-LAST:event_labelSalvarMouseClicked

    private void labelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharMouseClicked
        if(controleCadastroPagamento != null)
            controleCadastroPagamento.Fechar();
    }//GEN-LAST:event_labelFecharMouseClicked

    private void comboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxStatusActionPerformed
        if(controleCadastroPagamento != null)
            controleCadastroPagamento.ConfiguraStatus();
    }//GEN-LAST:event_comboBoxStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxDentista;
    private javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JComboBox<String> comboBoxTipoPagamento;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelDentista;
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelObservacao;
    private javax.swing.JLabel labelSalvar;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTipoPagamento;
    private javax.swing.JLabel labelValor;
    private javax.swing.JScrollPane scrollPaneObservacao;
    private javax.swing.JTextArea textAreaObservacao;
    private javax.swing.JTextField textFieldValor;
    // End of variables declaration//GEN-END:variables

}
