/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.modelo.TabelaPreco;
import javax.swing.JDialog;
import com.vandremurakami.odousys.controle.ControleCadastroTabelaPreco;

/**
 *
 * @author vandre
 */
public class panelCadastroTabelaPreco extends javax.swing.JPanel {

    
    private final ControleCadastroTabelaPreco controleCadastroTabelaPreco;
    
    /**
     * Creates new form panelCadastroPreco
     * @param dialog
     * @param tp
     */
    public panelCadastroTabelaPreco(JDialog dialog, TabelaPreco tp) {
        initComponents();
        controleCadastroTabelaPreco = new ControleCadastroTabelaPreco(dialog, this, tp);
    }
    
    public String getNome() {
        //o primeiro elemento da combobox não é válido
        return textFieldNome.getText();
    }
    
    public void setNome(String nome) {
        textFieldNome.setText(nome);
    }
    
    public boolean getAtivo() {
        return checkBoxAtivo.isSelected();
    }
    
    public void setAtivo(boolean ativo) {
        checkBoxAtivo.setSelected(ativo);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSalvar = new javax.swing.JLabel();
        labelFechar = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        checkBoxAtivo = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1060, 660));
        setMinimumSize(new java.awt.Dimension(1060, 660));
        setPreferredSize(new java.awt.Dimension(1060, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSalvar.setText("Salvar");
        labelSalvar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelSalvar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelSalvar.setOpaque(true);
        labelSalvar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSalvarMouseClicked(evt);
            }
        });
        add(labelSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        labelFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar.setText("Fechar");
        labelFechar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar.setOpaque(true);
        labelFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharMouseClicked(evt);
            }
        });
        add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        labelNome.setText("Nome:");
        add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 185, -1, -1));
        add(textFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 400, 25));

        checkBoxAtivo.setText("Tabela Ativa");
        add(checkBoxAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void labelSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalvarMouseClicked
        if(controleCadastroTabelaPreco != null)
            controleCadastroTabelaPreco.AdicionaAtualizaTabelaPreco();
    }//GEN-LAST:event_labelSalvarMouseClicked

    private void labelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharMouseClicked
        if(controleCadastroTabelaPreco != null)
            controleCadastroTabelaPreco.Fechar();
    }//GEN-LAST:event_labelFecharMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxAtivo;
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSalvar;
    private javax.swing.JTextField textFieldNome;
    // End of variables declaration//GEN-END:variables
}
