/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.modelo.Preco;
import javax.swing.JDialog;
import com.vandremurakami.odousys.controle.ControleCadastroPreco;
import com.vandremurakami.odousys.modelo.TabelaPreco;
import java.awt.event.KeyEvent;

/**
 *
 * @author vandre
 */
public class panelCadastroPreco extends javax.swing.JPanel {

    
    private final ControleCadastroPreco controleCadastroPreco;
    
    /**
     * Creates new form panelCadastroPreco
     * @param dialog
     * @param tabelaPreco
     * @param preco
     */
    public panelCadastroPreco(JDialog dialog, TabelaPreco tabelaPreco, Preco preco) {
        initComponents();
        controleCadastroPreco = new ControleCadastroPreco(dialog, this, tabelaPreco, preco);
    }
    
    public String getNome() {
        //o primeiro elemento da combobox não é válido
        return textFieldNome.getText();
    }
    
    public void setNome(String nome) {
        textFieldNome.setText(nome);
    }
    
    public String getValor() {
        return textFieldValor.getText().trim();
    }
    
    public void setValor(String valor) {
        textFieldValor.setText(valor);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSalvar = new javax.swing.JLabel();
        labelFechar = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        textFieldValor = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1060, 660));
        setMinimumSize(new java.awt.Dimension(1060, 660));
        setPreferredSize(new java.awt.Dimension(1060, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSalvar.setText("Salvar");
        labelSalvar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelSalvar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelSalvar.setOpaque(true);
        labelSalvar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSalvarMouseClicked(evt);
            }
        });
        add(labelSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        labelFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar.setText("Fechar");
        labelFechar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar.setOpaque(true);
        labelFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharMouseClicked(evt);
            }
        });
        add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        labelValor.setText("Valor:");
        add(labelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 235, -1, -1));
        add(textFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 200, 25));

        labelNome.setText("Nome:");
        add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 185, -1, -1));

        textFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldNomeKeyPressed(evt);
            }
        });
        add(textFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 400, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void labelSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalvarMouseClicked
        if(controleCadastroPreco != null)
            controleCadastroPreco.AdicionaAtualizaPreco();
    }//GEN-LAST:event_labelSalvarMouseClicked

    private void labelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharMouseClicked
        if(controleCadastroPreco != null)
            controleCadastroPreco.Fechar();
    }//GEN-LAST:event_labelFecharMouseClicked

    private void textFieldNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNomeKeyPressed
        int key = evt.getKeyCode();
        //tecla enter pressionada
        if (key == KeyEvent.VK_ENTER) {
            textFieldValor.requestFocus();
        }
    }//GEN-LAST:event_textFieldNomeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSalvar;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldValor;
    // End of variables declaration//GEN-END:variables
}
