/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vandremurakami.odousys.gui;

import com.vandremurakami.odousys.controle.ControleListaPaciente;
import java.awt.event.KeyEvent;
import javax.swing.JTable;
;

/**
 *
 * @author Vandre
 */
public class panelListarPaciente extends javax.swing.JPanel {
    
    final private ControleListaPaciente controleListaPaciente;

    /**
     * Creates new form painelListarPaciente
     */
    public panelListarPaciente() {
        initComponents();
        controleListaPaciente = new ControleListaPaciente(this);
    }
    
    public JTable getTabelaPaciente() {
        return tablePaciente; 
    }
    
    public String getFiltro() {
        return textFieldFiltro.getText().trim();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneTabelaPaciente = new javax.swing.JScrollPane();
        tablePaciente = new javax.swing.JTable();
        labelAdicionar = new javax.swing.JLabel();
        labelAbrir = new javax.swing.JLabel();
        labelRemover = new javax.swing.JLabel();
        labelFechar = new javax.swing.JLabel();
        labelFiltro = new javax.swing.JLabel();
        textFieldFiltro = new javax.swing.JTextField();
        labelLimparFiltro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1260, 630));
        setMinimumSize(new java.awt.Dimension(1260, 630));
        setPreferredSize(new java.awt.Dimension(1260, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPaneTabelaPaciente.setMaximumSize(new java.awt.Dimension(1085, 410));
        scrollPaneTabelaPaciente.setMinimumSize(new java.awt.Dimension(1085, 410));
        scrollPaneTabelaPaciente.setPreferredSize(new java.awt.Dimension(1085, 410));

        tablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Endereço", "Cidade", "Telefone", "Celular", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePaciente.setMaximumSize(null);
        tablePaciente.setMinimumSize(null);
        tablePaciente.setPreferredSize(null);
        tablePaciente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePaciente.getColumnModel().getColumn(0).setPreferredWidth(200);
        tablePaciente.getColumnModel().getColumn(1).setPreferredWidth(200);
        tablePaciente.getColumnModel().getColumn(2).setPreferredWidth(50);
        tablePaciente.getColumnModel().getColumn(3).setPreferredWidth(50);
        tablePaciente.getColumnModel().getColumn(4).setPreferredWidth(50);
        tablePaciente.getColumnModel().getColumn(5).setPreferredWidth(150);
        tablePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePacienteMouseClicked(evt);
            }
        });
        scrollPaneTabelaPaciente.setViewportView(tablePaciente);

        add(scrollPaneTabelaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 1085, 410));

        labelAdicionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdicionar.setText("Adicionar");
        labelAdicionar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAdicionar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAdicionar.setOpaque(true);
        labelAdicionar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAdicionarMouseClicked(evt);
            }
        });
        add(labelAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, -1, -1));

        labelAbrir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAbrir.setText("Abrir");
        labelAbrir.setMaximumSize(new java.awt.Dimension(90, 35));
        labelAbrir.setMinimumSize(new java.awt.Dimension(90, 35));
        labelAbrir.setOpaque(true);
        labelAbrir.setPreferredSize(new java.awt.Dimension(90, 35));
        labelAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAbrirMouseClicked(evt);
            }
        });
        add(labelAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, -1));

        labelRemover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRemover.setText("Remover");
        labelRemover.setMaximumSize(new java.awt.Dimension(90, 35));
        labelRemover.setMinimumSize(new java.awt.Dimension(90, 35));
        labelRemover.setOpaque(true);
        labelRemover.setPreferredSize(new java.awt.Dimension(90, 35));
        labelRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRemoverMouseClicked(evt);
            }
        });
        add(labelRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, -1, -1));

        labelFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechar.setText("Fechar");
        labelFechar.setMaximumSize(new java.awt.Dimension(90, 35));
        labelFechar.setMinimumSize(new java.awt.Dimension(90, 35));
        labelFechar.setOpaque(true);
        labelFechar.setPreferredSize(new java.awt.Dimension(90, 35));
        labelFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelFecharMouseClicked(evt);
            }
        });
        add(labelFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, -1, -1));

        labelFiltro.setText("Filtrar por nome:");
        add(labelFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        textFieldFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldFiltroKeyPressed(evt);
            }
        });
        add(textFieldFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 35, 250, 25));

        labelLimparFiltro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLimparFiltro.setText("Limpar");
        labelLimparFiltro.setMaximumSize(new java.awt.Dimension(90, 35));
        labelLimparFiltro.setMinimumSize(new java.awt.Dimension(90, 35));
        labelLimparFiltro.setOpaque(true);
        labelLimparFiltro.setPreferredSize(new java.awt.Dimension(90, 35));
        labelLimparFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLimparFiltroMouseClicked(evt);
            }
        });
        add(labelLimparFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tablePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePacienteMouseClicked
        if (evt.getClickCount() == 2) {
            if(controleListaPaciente != null)
                controleListaPaciente.CadastroAbrirPaciente();
        }
    }//GEN-LAST:event_tablePacienteMouseClicked

    private void labelAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAdicionarMouseClicked
        if(controleListaPaciente != null)
            controleListaPaciente.CadastroAdicionarPaciente();
    }//GEN-LAST:event_labelAdicionarMouseClicked

    private void labelAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAbrirMouseClicked
        if(controleListaPaciente != null)
            controleListaPaciente.CadastroAbrirPaciente();
    }//GEN-LAST:event_labelAbrirMouseClicked

    private void labelRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRemoverMouseClicked
        if(controleListaPaciente != null)
            controleListaPaciente.RemovePaciente();
    }//GEN-LAST:event_labelRemoverMouseClicked

    private void labelFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelFecharMouseClicked
        if(controleListaPaciente != null)
            controleListaPaciente.FecharListaPaciente();
    }//GEN-LAST:event_labelFecharMouseClicked

    private void labelLimparFiltroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLimparFiltroMouseClicked
        textFieldFiltro.setText("");
        if(controleListaPaciente != null)
            controleListaPaciente.PreencheTabelaPaciente();
    }//GEN-LAST:event_labelLimparFiltroMouseClicked

    private void textFieldFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldFiltroKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if(controleListaPaciente != null)
                controleListaPaciente.PreencheTabelaPaciente();
        }
    }//GEN-LAST:event_textFieldFiltroKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAbrir;
    private javax.swing.JLabel labelAdicionar;
    private javax.swing.JLabel labelFechar;
    private javax.swing.JLabel labelFiltro;
    private javax.swing.JLabel labelLimparFiltro;
    private javax.swing.JLabel labelRemover;
    private javax.swing.JScrollPane scrollPaneTabelaPaciente;
    private javax.swing.JTable tablePaciente;
    private javax.swing.JTextField textFieldFiltro;
    // End of variables declaration//GEN-END:variables
}
