-- Role: odousys
-- DROP ROLE odousys;

CREATE ROLE odousys WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'md57fd86afb86938b2b722dedf0f6ff4658';
